variables:
  # This registry is a linked docker container running on the same host
  # and configured in gitlab-ci-runner config.toml as a linked service
  DOCKER_REGISTRY: acs-public:5000
  PREFIX: /usr/

stages:
  - prepare
  - build
  - test
  - packaging
  - deploy

# Stage: prepare
##############################################################################

# Build docker image which is used to build & test VILLASnode
docker-images:
  stage: prepare
  before_script:
    - git submodule sync --recursive
    - git submodule update --recursive --init
    - docker info
  script:
    - docker pull fedora:latest
    - make docker-dev
    - docker tag -f villas-dev $DOCKER_REGISTRY/villas-dev:latest
    - docker push $DOCKER_REGISTRY/villas-dev:latest
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:
  stage: build
  script:
    - make
    - make tests
    - make install
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF}"
    paths:
      - build/release/
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker

docs:
  stage: build
  artifacts:
    name: "${CI_PROJECT_NAME}-doc-${CI_BUILD_REF}"
    paths:
      - build/release/doc/
  script:
    - make doc
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker


# Stage: test
##############################################################################

coverage:
  stage: test
  script:
    - make coverage COVERAGE=1
  artifacts:
    name: "${CI_PROJECT_NAME}-coverage-${CI_BUILD_REF}"
    paths:
      - build/release-coverage/coverage/
      - build/release-coverage/coverage.txt
      - build/release-coverage/coverage.xml
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker

unit:
  stage: test
  dependencies:
    - build
  script:
    - make run-unit-tests
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker

integration:
  stage: test
  dependencies:
    - build
  script:
    - make run-integration-tests
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker


# Stage: deliver
##############################################################################

website:
  stage: deploy
  script:
    - rsync -r web/ $DEPLOY_PATH/
  only:
    - develop
  tags:
    - villas-deploy

rpm:
  stage: packaging
  script:
    - make rpm
  tags:
    - shell
    - fedora

deliver:
  stage: deploy
  script:
    - rsync -r build/release/doc/html/ $DEPLOY_HOST:$DEPLOY_PATH/doc/$CI_BUILD_REF_NAME/
    - rsync -r build/release-coverage/coverage/ $DEPLOY_HOST:$DEPLOY_PATH/coverage/$CI_BUILD_REF_NAME/
    - rsync -r build/release/packaging/rpm/RPMS $DEPLOY_HOST:$DEPLOY_PATH/../packages
    - ssh $DEPLOY_HOST createrepo $DEPLOY_PATH/../packages
  dependencies:
   - docs
   - coverage
   - rpm
  tags:
    - villas-deploy

