variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  PREFIX: /usr/
  RSYNC_OPTS: --recursive --ignore-missing-args --chown $DEPLOY_USER:$DEPLOY_USER

stages:
  - prepare
  - build
  - test
  - deploy

# Stage: prepare
##############################################################################

# Build docker image which is used to build & test VILLASnode
docker-dev:
  stage: prepare
  before_script:
    - docker info
  script:
    - docker pull fedora:latest
    - docker build -f Dockerfile.dev -t villas-node-dev .
    - docker tag -f villas-node-dev $DOCKER_REGISTRY/villas-node-dev:latest
    - docker push $DOCKER_REGISTRY/villas-node-dev:latest
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:
  stage: build
  script:
    - make
    - make tests
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF}"
    paths:
      - build/release/
  image: $DOCKER_REGISTRY/villas-node-dev
  tags:
    - docker

docs:
  stage: build
  artifacts:
    name: "${CI_PROJECT_NAME}-doc-${CI_BUILD_REF}"
    paths:
      - build/release/doc/
  script:
    - make doc
  image: $DOCKER_REGISTRY/villas-node-dev
  tags:
    - docker

packages:
  stage: build
  before_script:
    - dnf -y config-manager --add-repo https://$DEPLOY_USER:$DEPLOY_PASS@$DEPLOY_HOST/packages/villas.repo
    - dnf -y --refresh install libwebsockets-devel libxil-devel
  script:
    - make dist
    - make rpm-villas-node
  only:
    - tags
    - triggers
  artifacts:
    name: "${CI_PROJECT_NAME}-packages-${CI_BUILD_REF}"
    paths:
      - build/release/packaging/*.tar.gz
      - build/release/packaging/rpm/RPMS/
  image: $DOCKER_REGISTRY/villas-node-dev
  tags:
    - docker


# Stage: test
##############################################################################

coverage:
  stage: test
  script:
    - make coverage COVERAGE=1
  artifacts:
    name: "${CI_PROJECT_NAME}-coverage-${CI_BUILD_REF}"
    paths:
      - build/release-coverage/coverage/
      - build/release-coverage/coverage.txt
      - build/release-coverage/coverage.xml
  image: $DOCKER_REGISTRY/villas-node-dev
  coverage: '/lines: (\d+\.\d+\%)/'
  tags:
    - docker

unit:
  stage: test
  dependencies:
    - build
  script:
    - make run-unit-tests
  image: $DOCKER_REGISTRY/villas-node-dev
  tags:
    - docker

integration:
  stage: test
  dependencies:
    - build
  before_script:
    - make install
  script:
    - make run-integration-tests
  artifacts:
    name: "${CI_PROJECT_NAME}-integration-tests-${CI_BUILD_REF}"
    when: always
    paths:
      - build/release/tests/integration/
  image: $DOCKER_REGISTRY/villas-node-dev
  tags:
    - docker


# Stage: deliver
##############################################################################

docker:
  stage: deploy
  script:
    - make docker
    - docker tag -f villas $DOCKER_REGISTRY/villas:latest
    - docker push $DOCKER_REGISTRY/villas:latest
  dependencies:
    - packages
  only:
    - tags
  tags:
    - shell
    - linux

website:
  stage: deploy
  script:
    - rsync -r web/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/
  only:
    - develop
  tags:
    - villas-deploy

deliver:
  stage: deploy
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST mkdir -p $DEPLOY_PATH/{coverage,doc}/$CI_BUILD_REF_NAME/
    - rsync $RSYNC_OPTS build/release-coverage/coverage/  $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/coverage/$CI_BUILD_REF_NAME/
    - rsync $RSYNC_OPTS build/release/doc/html/           $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/doc/$CI_BUILD_REF_NAME/
  dependencies:
    - docs
    - coverage
    - packages
  tags:
    - villas-deploy

deliver-packages:
  stage: deploy
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST mkdir -p $DEPLOY_PATH/{dist,../packages}
    - rsync $RSYNC_OPTS build/release/packaging/rpm/RPMS/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/../packages/
    - rsync $RSYNC_OPTS build/release/packaging/*.tar.gz  $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/dist/
    - ssh $DEPLOY_USER@$DEPLOY_HOST createrepo $DEPLOY_PATH/../packages
  dependencies:
    - packages
  only:
    - tags
  tags:
    - villas-deploy
  