variables:
  PREFIX: /usr/
  BUILDDIR: build/release

stages:
  - prepare
  - build
  - test
  - deploy

# Stage: prepare
##############################################################################

# Build docker image which is used to build & test VILLASnode
docker-dev:
  stage: prepare
  before_script:
    - docker info
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - docker pull fedora:latest
    - make docker-dev
    - docker tag -f villas-dev $DOCKER_REGISTRY/villas-dev:latest
    - docker push $DOCKER_REGISTRY/villas-dev:latest
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:
  stage: build
  script:
    - make
    - make tests
    - make install
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF}"
    paths:
      - $BUILDDIR/
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker

docs:
  stage: build
  artifacts:
    name: "${CI_PROJECT_NAME}-doc-${CI_BUILD_REF}"
    paths:
      - $BUILDDIR/doc/
  script:
    - make doc
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker

packages:
  stage: build
  before_script:
    - curl -s https://$DEPLOY_USER:$DEPLOY_PASS@$DEPLOY_HOST/packages/villas.repo > /etc/yum.repos.d/villas.repo
    - dnf -y --refresh install libwebsockets-devel libxil-devel
  script:
    - make dist
    - make rpm-villas
  artifacts:
    name: "${CI_PROJECT_NAME}-packages-${CI_BUILD_REF}"
    paths:
      - $BUILDDIR/packaging/
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker


# Stage: test
##############################################################################

coverage:
  stage: test
  script:
    - make coverage COVERAGE=1
  artifacts:
    name: "${CI_PROJECT_NAME}-coverage-${CI_BUILD_REF}"
    paths:
      - build/release-coverage/coverage/
      - build/release-coverage/coverage.txt
      - build/release-coverage/coverage.xml
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker

unit:
  stage: test
  dependencies:
    - build
  script:
    - make run-unit-tests
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker

integration:
  stage: test
  dependencies:
    - build
  script:
    - make run-integration-tests
  artifacts:
    name: "${CI_PROJECT_NAME}-integration-tests-${CI_BUILD_REF}"
    paths:
      - BUILDDIR/tests/integration/
  image: $DOCKER_REGISTRY/villas-dev
  tags:
    - docker


# Stage: deliver
##############################################################################

website:
  stage: deploy
  script:
    - rsync -r web/ $DEPLOY_PATH/
  only:
    - develop
  tags:
    - villas-deploy

docker:
  stage: deploy
  script:
    - make docker
    - docker tag -f villas $DOCKER_REGISTRY/villas:latest
    - docker push $DOCKER_REGISTRY/villas:latest
  dependencies:
   - packages
  tags:
    - shell
    - linux

deliver:
  stage: deploy
  script:
    - rsync -r build/release-coverage/coverage/ $DEPLOY_HOST:$DEPLOY_PATH/coverage/$CI_BUILD_REF_NAME/
    - rsync -r $BUILDDIR/doc/html/ $DEPLOY_HOST:$DEPLOY_PATH/doc/$CI_BUILD_REF_NAME/
    - rsync -r $BUILDDIR/packaging/rpm/RPMS $DEPLOY_HOST:$DEPLOY_PATH/../packages
    - ssh $DEPLOY_HOST createrepo $DEPLOY_PATH/../packages
  dependencies:
   - docs
   - coverage
   - packages
  tags:
    - villas-deploy
